version: '3.8'

services:
  # Personal Profile Website
  profile-app:
    build: .
    ports:
      - "8080:80"
    restart: unless-stopped
    container_name: rushford-profile
    networks:
      - lab12-network

  # Todo Application - Custom built
  todo-app:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./todo-app:/usr/share/nginx/html
    restart: unless-stopped
    container_name: todo-application
    networks:
      - lab12-network
    depends_on:
      - profile-app

  # Advanced Todo Application - Using Vikunja (popular GitHub todo app)
  vikunja-app:
    image: vikunja/vikunja:latest
    ports:
      - "8082:3456"
    environment:
      - VIKUNJA_DATABASE_TYPE=sqlite
      - VIKUNJA_DATABASE_PATH=/app/data/vikunja.db
      - VIKUNJA_SERVICE_FRONTENDURL=http://localhost:8082
      - VIKUNJA_SERVICE_ENABLEREGISTRATION=true
    volumes:
      - vikunja-data:/app/data
      - vikunja-files:/app/files
    restart: unless-stopped
    container_name: advanced-todo-app
    networks:
      - lab12-network
    depends_on:
      - todo-app

networks:
  lab12-network:
    driver: bridge

volumes:
  vikunja-data:
    driver: local
  vikunja-files:
    driver: local
