name: Simple HTML Linting

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint-html:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install HTML Linter
      run: npm install -g htmllint-cli

    - name: Lint HTML files
      run: |
        echo "Linting profile.html..."
        htmllint profile.html
        
        echo "Linting todo-app/index.html..."
        htmllint todo-app/index.html
        
        echo "✅ All HTML files are well-formed!"

    - name: Success Notification
      if: success()
      run: echo "🎉 HTML linting job completed successfully." 